### ISSUE TITLE
pip 9.0.3 needs to be installed on remote hosts as well

### ISSUE THREAD

**Issue by rihabbanday** [intel/container-experience-kits#68]
In order for a successful BMRA deployment, pip version 9.0.3 needs to be installed on the remote/k8s hosts. With newer pip versions, the installation fails. 
For example, the following could be added in `roles/bootstrap/install_packages/tasks/rhel.yml` to get rid of the issue:
```
- name: Install recommended pip version 
   pip:
     name:
       - pip==9.0.3 
```

It would be also good to mention this in the documentation, which currently only mentions to have pip 9.0.3 on the Ansible machine.
