### ISSUE TITLE
Retrying failed CEK deployment breaks CMK

### ISSUE THREAD

**Issue by moss2k13** [intel/container-experience-kits#71]
Hello,
My deployment (v21.08) failed on TAS installation due my config error.
When I retried the deployment after fixing TAS config, CMK pods went down to `CrashLoopBackOff` with 401 Unauthorized errors after TLS certs for CMK webhook have been recreated.
I will provide full ansible log later on with more details about the issue.

**Comment by calinghe** [comment]
Hello and thanks much for your input.  Did you try please using the cleanup playbook (redeploy_cleanup.yml) prior to trying to redeploy?  Let us know please if this addresses the issue.

**Comment by moss2k13** [comment]
After creating (as it does not exist) and triggering below playbook `redeploy_cmk_cleanup.yml`:
```
---
- name: prepare for cmk redeployment
  hosts: kube_control_plane
  tasks:
    - include_role:
        name: roles/cmk_install
        tasks_from: reset
      when: kubernetes | default(true)
```
 `cmk` redeployment works fine, thanks!
